2021-05-25 08:32:11.810 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-25 08:32:11.816 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-25 08:32:11.839 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-25 08:32:11.839 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-25 08:32:11.852 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-25 08:32:11.852 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-25 08:32:11.979 [warning] <0.921.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-25 08:32:12.050 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-25 08:33:33.427 [error] <0.1054.0> CRASH REPORT Process <0.1054.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:33:33.433 [error] <0.1054.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.1053.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:37:39.612 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-25 08:37:39.618 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-25 08:37:39.625 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-25 08:37:39.625 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-25 08:37:39.625 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-25 08:37:39.626 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-25 08:37:39.641 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-25 08:37:39.641 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-25 08:37:39.654 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-25 08:37:39.656 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-25 08:37:39.785 [warning] <0.593.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-25 08:37:39.868 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-25 08:39:03.297 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:39:03.303 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:45:46.559 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-25 08:45:46.565 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-25 08:45:46.596 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-25 08:45:46.596 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-25 08:45:46.615 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-25 08:45:46.618 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-25 08:45:46.768 [warning] <0.593.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-25 08:45:46.871 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-25 08:46:42.377 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<...>>}}],...},...]},...},...},...}
2021-05-25 08:46:42.384 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<"...">>}}],...},...]},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> CRASH REPORT Process <0.726.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> CRASH REPORT Process <0.728.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],...}],...},...]},...},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
