2021-05-25 08:32:11.810 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-25 08:32:11.816 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-25 08:32:11.824 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-25 08:32:11.839 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-25 08:32:11.839 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-25 08:32:11.852 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-25 08:32:11.852 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-25 08:32:11.979 [warning] <0.921.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-25 08:32:12.050 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-25 08:33:33.427 [error] <0.1054.0> CRASH REPORT Process <0.1054.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:33:33.433 [error] <0.1054.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.1053.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621920813,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621920813},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:37:39.612 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-25 08:37:39.618 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-25 08:37:39.625 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-25 08:37:39.625 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-25 08:37:39.625 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-25 08:37:39.626 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-25 08:37:39.641 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-25 08:37:39.641 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-25 08:37:39.654 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-25 08:37:39.656 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-25 08:37:39.785 [warning] <0.593.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-25 08:37:39.868 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-25 08:39:03.297 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...},...}
2021-05-25 08:39:03.303 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921143,description => <<"after injury">>,name => <<"leg pain">>,updated_at => 1621921143},id => <<"7">>,links => #{self => <<"http://localhost/symptom/7">>},relationships => #{},type => <<"symptom">>},included => [],links => #{...}}],...},...]},...},...}
2021-05-25 08:45:46.559 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-25 08:45:46.565 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-25 08:45:46.576 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-25 08:45:46.596 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-25 08:45:46.596 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-25 08:45:46.615 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-25 08:45:46.618 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-25 08:45:46.768 [warning] <0.593.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-25 08:45:46.871 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-25 08:46:42.377 [error] <0.725.0> CRASH REPORT Process <0.725.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<...>>}}],...},...]},...},...},...}
2021-05-25 08:46:42.384 [error] <0.725.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921602,disease => <<"wer">>,drug => <<"DVF">>,updated_at => 1621921602},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => #{self => <<"...">>}}],...},...]},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> CRASH REPORT Process <0.726.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...},...}
2021-05-25 08:47:20.740 [error] <0.726.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => #{attributes => #{created_at => 1621921640,disease => <<"wer_updated">>,drug => <<"DVF_updated">>,updated_at => 1621921640},id => <<"23">>,links => #{self => <<"http://localhost/treatment/23">>},relationships => #{},type => <<"treatment">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> CRASH REPORT Process <0.728.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],...}],...},...]},...},...},...}
2021-05-25 08:48:15.751 [error] <0.728.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1621921695,description => <<"response to good joke">>,name => <<"laughter">>,updated_at => 1621921695},id => <<"23">>,links => #{self => <<"http://localhost/symptom/23">>},relationships => #{},type => <<"symptom">>},included => [],links => ...}],...},...]},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> CRASH REPORT Process <0.729.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-25 08:48:33.611 [error] <0.729.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.724.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:20:44.130 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 08:20:44.136 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 08:20:44.147 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 08:20:44.147 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 08:20:44.147 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 08:20:44.147 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 08:20:44.163 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 08:20:44.163 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 08:20:44.178 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 08:20:44.180 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 08:20:44.404 [warning] <0.392.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 08:20:44.531 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 08:21:53.273 [error] <0.529.0> CRASH REPORT Process <0.529.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:21:53.282 [error] <0.529.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.528.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:22:10.428 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:22:10.428 [error] <0.530.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.528.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:32:33.635 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 08:32:33.640 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 08:32:33.647 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 08:32:33.648 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 08:32:33.648 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 08:32:33.648 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 08:32:33.663 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 08:32:33.663 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 08:32:33.684 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 08:32:33.686 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 08:32:33.887 [warning] <0.392.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 08:32:34.022 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 08:34:18.854 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:34:18.863 [error] <0.524.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.523.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:37:51.198 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 08:37:51.206 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 08:37:51.214 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 08:37:51.214 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 08:37:51.214 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 08:37:51.214 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 08:37:51.229 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 08:37:51.229 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 08:37:51.242 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 08:37:51.245 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 08:37:51.432 [warning] <0.392.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 08:37:51.534 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 08:39:23.991 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 08:39:23.997 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 08:39:24.005 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 08:39:24.005 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 08:39:24.006 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 08:39:24.006 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 08:39:24.022 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 08:39:24.022 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 08:39:24.037 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 08:39:24.039 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 08:39:24.225 [warning] <0.392.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 08:39:24.340 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 08:40:12.763 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:40:12.770 [error] <0.524.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.523.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 08:42:45.313 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:42:45.314 [error] <0.527.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:42:55.003 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:42:55.003 [error] <0.528.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.526.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:45.802 [error] <0.531.0> CRASH REPORT Process <0.531.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:45.802 [error] <0.531.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:54.388 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:54.388 [error] <0.532.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:55.565 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:55.565 [error] <0.533.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:56.054 [error] <0.534.0> CRASH REPORT Process <0.534.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:56.054 [error] <0.534.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:56.471 [error] <0.535.0> CRASH REPORT Process <0.535.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:56.471 [error] <0.535.0> Cowboy stream 5 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:56.736 [error] <0.536.0> CRASH REPORT Process <0.536.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:56.736 [error] <0.536.0> Cowboy stream 6 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.063 [error] <0.537.0> CRASH REPORT Process <0.537.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.063 [error] <0.537.0> Cowboy stream 7 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.346 [error] <0.538.0> CRASH REPORT Process <0.538.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.346 [error] <0.538.0> Cowboy stream 8 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.628 [error] <0.539.0> CRASH REPORT Process <0.539.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.628 [error] <0.539.0> Cowboy stream 9 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:57.901 [error] <0.540.0> CRASH REPORT Process <0.540.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:57.902 [error] <0.540.0> Cowboy stream 10 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:58.159 [error] <0.541.0> CRASH REPORT Process <0.541.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:58.160 [error] <0.541.0> Cowboy stream 11 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:58.517 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:58.517 [error] <0.542.0> Cowboy stream 12 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:44:58.810 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:44:58.810 [error] <0.543.0> Cowboy stream 13 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.530.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:46:20.514 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:46:20.514 [error] <0.546.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:46:21.419 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:46:21.420 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:47:02.632 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => #{attributes => #{created_at => 1622094422,rating => 3,text => <<"he did a great job reparing my knee!">>,updated_at => 1622094422},id => <<"6">>,links => #{self => <<"http://localhost/feedback/6">>},relationships => #{},type => <<"feedback">>},included => [],...}],...},...]},...},...},...}
2021-05-27 08:47:02.632 [error] <0.548.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => #{attributes => #{created_at => 1622094422,rating => 3,text => <<"he did a great job reparing my knee!">>,updated_at => 1622094422},id => <<"6">>,links => #{self => <<"http://localhost/feedback/6">>},relationships => #{},type => <<"feedback">>},included => [],links => ...}],...},...]},...},...}
2021-05-27 08:47:14.860 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-27 08:47:14.861 [error] <0.549.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.FeedbackView'},[{'Elixir.Api.Views.FeedbackView',id,[#{data => [#{attributes => #{created_at => 1621919693,rating => 5,text => <<"Really grateful for the doctor, he did a great job reparing my knee!">>,updated_at => 1621919693},id => <<"12">>,links => #{self => <<"http://localhost/feedback/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-27 08:47:50.944 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 08:47:50.951 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 08:47:50.958 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 08:47:50.958 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 08:47:50.958 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 08:47:50.958 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 08:47:50.974 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 08:47:50.974 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 08:47:50.988 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 08:47:50.990 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 08:47:51.203 [warning] <0.392.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 08:47:51.292 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 08:48:22.991 [error] <0.524.0> CRASH REPORT Process <0.524.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 08:48:22.999 [error] <0.524.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.523.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 11:12:44.539 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 11:12:44.544 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 11:12:44.552 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 11:12:44.552 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 11:12:44.552 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 11:12:44.552 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 11:12:44.567 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 11:12:44.567 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 11:12:44.580 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 11:12:44.583 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 11:12:44.711 [warning] <0.599.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 11:12:44.795 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 11:14:11.912 [error] <0.731.0> CRASH REPORT Process <0.731.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:14:11.919 [error] <0.731.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.730.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:16:45.705 [error] <0.735.0> CRASH REPORT Process <0.735.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:16:45.705 [error] <0.735.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.734.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:17:10.376 [error] <0.736.0> CRASH REPORT Process <0.736.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:17:10.376 [error] <0.736.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.734.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:17:45.357 [error] <0.737.0> CRASH REPORT Process <0.737.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:17:45.358 [error] <0.737.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.734.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:18:23.862 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 11:18:23.869 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 11:18:23.881 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 11:18:23.881 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 11:18:23.881 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 11:18:23.881 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 11:18:23.902 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 11:18:23.902 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 11:18:23.919 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 11:18:23.922 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 11:18:24.106 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 11:18:24.206 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 11:19:43.552 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [{<<"Content-type">>,<<"application/json">>}]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,...},...]},...]},...},...},...}
2021-05-27 11:19:43.558 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [{<<"Content-type">>,<<"application/json">>}]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"l..."},...]},...]},...},...}
2021-05-27 11:23:21.694 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 11:23:21.700 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 11:23:21.710 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 11:23:21.710 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 11:23:21.710 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 11:23:21.710 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 11:23:21.727 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 11:23:21.727 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 11:23:21.741 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 11:23:21.743 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 11:23:21.898 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 11:23:21.996 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 11:24:34.725 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:24:34.731 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:25:02.343 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:25:02.343 [error] <0.544.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:27:29.820 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:27:29.820 [error] <0.548.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.547.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:27:43.461 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...},...}
2021-05-27 11:27:43.461 [error] <0.549.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.547.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...}
2021-05-27 11:32:47.456 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:32:47.458 [error] <0.553.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.552.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:37:57.974 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 11:37:57.979 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 11:37:57.990 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 11:37:57.990 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 11:37:57.991 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 11:37:57.991 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 11:37:58.008 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 11:37:58.008 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 11:37:58.025 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 11:37:58.030 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 11:37:58.217 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 11:37:58.311 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 11:39:28.473 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:39:28.479 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:40:45.338 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:40:45.339 [error] <0.546.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:40:52.865 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:40:52.865 [error] <0.547.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.545.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,32}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:49:39.098 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 11:49:39.107 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 11:49:39.118 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 11:49:39.118 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 11:49:39.119 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 11:49:39.119 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 11:49:39.137 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 11:49:39.137 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 11:49:39.152 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 11:49:39.155 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 11:49:39.313 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 11:49:39.422 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 11:50:43.779 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 11:50:43.785 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 11:55:20.712 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 11:55:20.718 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 11:55:20.726 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 11:55:20.726 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 11:55:20.727 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 11:55:20.727 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 11:55:20.742 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 11:55:20.742 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 11:55:20.757 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 11:55:20.759 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 11:55:20.896 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 11:55:20.992 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 12:01:55.913 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 12:01:55.919 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 12:01:55.928 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 12:01:55.928 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 12:01:55.928 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 12:01:55.928 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 12:01:55.944 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 12:01:55.944 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 12:01:55.956 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 12:01:55.958 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 12:01:56.109 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 12:01:56.203 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 12:03:15.667 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:03:15.672 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:10:42.144 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 12:10:42.149 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 12:10:42.158 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 12:10:42.158 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 12:10:42.158 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 12:10:42.158 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 12:10:42.173 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 12:10:42.173 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 12:10:42.185 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 12:10:42.187 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 12:10:42.341 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 12:10:42.430 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 12:11:47.273 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,34}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:11:47.280 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,34}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:17:45.474 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:17:45.474 [error] <0.548.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.547.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 12:18:32.288 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-27 12:18:32.294 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-27 12:18:32.304 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-27 12:18:32.304 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-27 12:18:32.304 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-27 12:18:32.304 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-27 12:18:32.321 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-27 12:18:32.321 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-27 12:18:32.336 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-27 12:18:32.338 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-27 12:18:32.478 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-27 12:18:32.575 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-27 12:20:19.898 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:20:19.905 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:20:29.672 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:20:29.672 [error] <0.545.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.544.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 12:25:44.957 [error] <0.553.0> CRASH REPORT Process <0.553.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:25:44.957 [error] <0.553.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.552.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:26:08.130 [error] <0.555.0> CRASH REPORT Process <0.555.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:26:08.131 [error] <0.555.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.554.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-27 12:26:20.243 [error] <0.558.0> CRASH REPORT Process <0.558.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-27 12:26:20.243 [error] <0.558.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.554.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => []},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-27 12:26:22.967 [error] <0.559.0> CRASH REPORT Process <0.559.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-27 12:26:22.968 [error] <0.559.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.554.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 07:46:29.351 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-28 07:46:29.356 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-28 07:46:29.364 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-28 07:46:29.364 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-28 07:46:29.364 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-28 07:46:29.364 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-28 07:46:29.379 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-28 07:46:29.379 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-28 07:46:29.390 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-28 07:46:29.392 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-28 07:46:29.559 [warning] <0.392.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-28 07:46:29.648 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-28 07:48:53.149 [error] <0.530.0> CRASH REPORT Process <0.530.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 07:48:53.156 [error] <0.530.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.529.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 07:49:05.203 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [<<>>]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...},...}
2021-05-28 07:49:05.203 [error] <0.532.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.529.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.CaseClauseError',term => [<<>>]},[{'Elixir.Endpoints.SymptomEndpoint','-do_match/4-fun-2-',2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,33}]},{'Elixir.Endpoints.SymptomEndpoint',dispatch,2,[{file,"lib/plug/router.ex"},{line,284}]},{'Elixir.Endpoints.SymptomEndpoint',plug_builder_call,2,[{file,"lib/api_test/endpoints/symptom_endpoint.ex"},{line,1}]},{'Elixir.Plug',forward,4,[{file,"lib/plug.ex"},{line,168}]},{'Elixir.Api.Router',...},...]},...},...}
2021-05-28 07:49:16.226 [error] <0.533.0> CRASH REPORT Process <0.533.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 07:49:16.227 [error] <0.533.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.529.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 07:58:58.404 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-28 07:58:58.411 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-28 07:58:58.420 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-28 07:58:58.420 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-28 07:58:58.421 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-28 07:58:58.421 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-28 07:58:58.435 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-28 07:58:58.435 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-28 07:58:58.448 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-28 07:58:58.450 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-28 07:58:58.592 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-28 07:58:58.689 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-28 07:59:49.673 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Parsers.UnsupportedMediaTypeError',media_type => <<"application/octet-stream">>,plug_status => 415},[{'Elixir.Plug.Parsers',reduce,8,[{file,"lib/plug/parsers.ex"},{line,357}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Downloads/facultate_stef/master_anul..."},...]},...]},...},...},...}
2021-05-28 07:59:49.680 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Plug.Parsers.UnsupportedMediaTypeError',media_type => <<"application/octet-stream">>,plug_status => 415},[{'Elixir.Plug.Parsers',reduce,8,[{file,"lib/plug/parsers.ex"},{line,357}]},{'Elixir.Api.Router',plug_builder_call,2,[{file,"lib/api_test/router.ex"},{line,1}]},{'Elixir.Plug.Cowboy.Handler',init,2,[{file,"lib/plug/cowboy/handler.ex"},{line,12}]},{cowboy_handler,execute,2,[{file,"c:/Users/leluts/Downloads/facultate_stef/master_anul1_..."},...]},...]},...},...}
2021-05-28 08:01:48.301 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-28 08:01:48.307 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-28 08:01:48.316 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-28 08:01:48.316 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-28 08:01:48.316 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-28 08:01:48.316 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-28 08:01:48.331 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-28 08:01:48.331 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-28 08:01:48.344 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-28 08:01:48.346 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-28 08:01:48.494 [warning] <0.411.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-28 08:01:48.610 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-28 08:02:49.837 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 08:02:49.845 [error] <0.543.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 08:03:10.456 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622178190,description => <<"tre">>,name => <<"abc">>,updated_at => 1622178190},id => <<"10">>,links => #{self => <<"http://localhost/symptom/10">>},relationships => #{},type => <<"symptom">>},included => [],links => #{self => <<"...">>}}],...},...]},...},...},...}
2021-05-28 08:03:10.456 [error] <0.546.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622178190,description => <<"tre">>,name => <<"abc">>,updated_at => 1622178190},id => <<"10">>,links => #{self => <<"http://localhost/symptom/10">>},relationships => #{},type => <<"symptom">>},included => [],links => #{self => <<"ht...">>}}],...},...]},...},...}
2021-05-28 08:03:21.581 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 08:03:21.581 [error] <0.547.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.542.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 08:25:06.578 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-28 08:25:06.584 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-28 08:25:06.593 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-28 08:25:06.593 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-28 08:25:06.593 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-28 08:25:06.593 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-28 08:25:06.609 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-28 08:25:06.609 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-28 08:25:06.622 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-28 08:25:06.624 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-28 08:25:06.759 [warning] <0.617.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-28 08:25:06.845 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-28 08:28:10.957 [error] <0.750.0> CRASH REPORT Process <0.750.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...}],...},...]},...},...},...}
2021-05-28 08:28:10.963 [error] <0.750.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => <<..>>},...}],...},...]},...},...}
2021-05-28 08:28:28.344 [error] <0.751.0> CRASH REPORT Process <0.751.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...}],...}],...},...]},...},...},...}
2021-05-28 08:28:28.344 [error] <0.751.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...}],...}],...},...]},...},...}
2021-05-28 08:29:03.405 [error] <0.754.0> CRASH REPORT Process <0.754.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179743,date => <<"12-04-2021">>,doctor => <<"Dr Jeffrey Kabouli">>,patient => <<"Alex Porinton">>,updated_at => 1622179743},id => <<"10">>,links => #{self => <<"http://localhost/appointment/10">>},relationships => #{},...},...}],...},...]},...},...},...}
2021-05-28 08:29:03.405 [error] <0.754.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => #{attributes => #{created_at => 1622179743,date => <<"12-04-2021">>,doctor => <<"Dr Jeffrey Kabouli">>,patient => <<"Alex Porinton">>,updated_at => 1622179743},id => <<"10">>,links => #{self => <<"http://localhost/appointment/10">>},relationships => #{},type => ...},...}],...},...]},...},...}
2021-05-28 08:29:13.480 [error] <0.756.0> CRASH REPORT Process <0.756.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-28 08:29:13.481 [error] <0.756.0> Cowboy stream 4 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-28 08:29:25.263 [error] <0.758.0> CRASH REPORT Process <0.758.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"...">>},...],...}],...},...]},...},...},...}
2021-05-28 08:29:25.264 [error] <0.758.0> Cowboy stream 5 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.749.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1621839564,description => <<"body temperature over 37.2 degrees Celsius">>,name => <<"fever_updated">>,updated_at => 1621839564},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"sy...">>},...],...}],...},...]},...},...}
2021-05-28 08:30:56.408 [error] <0.761.0> CRASH REPORT Process <0.761.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.HospitalView'},[{'Elixir.Api.Views.HospitalView',id,[#{data => [#{attributes => #{available_beds => 12,city => <<"Bucharest">>,created_at => 1621833653,name => <<"Spital 1">>,specialization => <<"Oncologic">>,updated_at => 1621833653},id => <<"11">>,links => #{self => <<"http://localhost/hospital/11">>},relationships => #{},...},...],...}],...},...]},...},...},...}
2021-05-28 08:30:56.408 [error] <0.761.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.HospitalView'},[{'Elixir.Api.Views.HospitalView',id,[#{data => [#{attributes => #{available_beds => 12,city => <<"Bucharest">>,created_at => 1621833653,name => <<"Spital 1">>,specialization => <<"Oncologic">>,updated_at => 1621833653},id => <<"11">>,links => #{self => <<"http://localhost/hospital/11">>},relationships => #{},...},...],...}],...},...]},...},...}
2021-05-28 08:31:06.217 [error] <0.764.0> CRASH REPORT Process <0.764.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...},...}
2021-05-28 08:31:06.217 [error] <0.764.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.TreatmentView'},[{'Elixir.Api.Views.TreatmentView',id,[#{data => [#{attributes => #{created_at => 1621401032,disease => <<"fever">>,drug => <<"aspirin">>,updated_at => 1621401032},id => <<"2">>,links => #{self => <<"http://localhost/treatment/2">>},relationships => #{},type => <<"treatment">>},#{attributes => #{created_at => ...,...},...},...],...}],...},...]},...},...}
2021-05-28 08:31:22.169 [error] <0.766.0> CRASH REPORT Process <0.766.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...},...}
2021-05-28 08:31:22.170 [error] <0.766.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.760.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.AppointmentView'},[{'Elixir.Api.Views.AppointmentView',id,[#{data => [#{attributes => #{created_at => 1622179690,date => <<"12-05-2021">>,doctor => <<"Dr Rahjeed Kabouli">>,patient => <<"John Reed">>,updated_at => 1622179690},id => <<"12">>,links => #{self => <<"http://localhost/appointment/12">>},relationships => #{},type => ...},...],...}],...},...]},...},...}
2021-05-31 08:37:24.521 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-31 08:37:24.528 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-31 08:37:24.534 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-31 08:37:24.534 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-31 08:37:24.534 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-31 08:37:24.534 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-31 08:37:24.552 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-31 08:37:24.552 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-31 08:37:24.565 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-31 08:37:24.566 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-31 08:37:24.614 [warning] <0.4440.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-31 08:37:24.668 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-31 08:53:06.104 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-31 08:53:06.111 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-31 08:53:06.117 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-31 08:53:06.117 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-31 08:53:06.117 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-31 08:53:06.117 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-31 08:53:06.134 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-31 08:53:06.134 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-31 08:53:06.146 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-31 08:53:06.148 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-31 08:53:06.299 [warning] <0.391.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-31 08:53:06.377 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-31 08:54:51.963 [error] <0.523.0> CRASH REPORT Process <0.523.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [],included => [],links => #{self => <<"http://localhost/symptom">>}}],[{file,"lib/views/symptom_view.ex"},{line,2}]},{'Elixir.JSONAPI.Serializer',encode_data,4,[{file,"lib/jsonapi/serializer.ex"},{line,44}]},{'Elixir.JSONAPI.Serializer',serialize,3,[{file,"lib/j..."},...]},...]},...},...},...}
2021-05-31 08:54:51.967 [error] <0.523.0> Cowboy stream 1 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.522.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [],included => [],links => #{self => <<"http://localhost/symptom">>}}],[{file,"lib/views/symptom_view.ex"},{line,2}]},{'Elixir.JSONAPI.Serializer',encode_data,4,[{file,"lib/jsonapi/serializer.ex"},{line,44}]},{'Elixir.JSONAPI.Serializer',serialize,3,[{file,"lib/jso..."},...]},...]},...},...}
2021-05-31 08:55:26.791 [error] <0.527.0> CRASH REPORT Process <0.527.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>},...}],...},...]},...},...},...}
2021-05-31 08:55:26.792 [error] <0.527.0> Cowboy stream 2 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.522.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => #{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>},included => ...,...}],...},...]},...},...}
2021-05-31 08:55:44.005 [error] <0.528.0> CRASH REPORT Process <0.528.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>}],...}],...},...]},...},...},...}
2021-05-31 08:55:44.006 [error] <0.528.0> Cowboy stream 3 with ranch listener 'Elixir.Api.Router.HTTP' and connection process <0.522.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.FunctionClauseError',args => nil,arity => 1,clauses => nil,function => id,kind => nil,module => 'Elixir.Api.Views.SymptomView'},[{'Elixir.Api.Views.SymptomView',id,[#{data => [#{attributes => #{created_at => 1622440526,description => <<"could be a symptom for a lot of things">>,name => <<"coughing">>,updated_at => 1622440526},id => <<"2">>,links => #{self => <<"http://localhost/symptom/2">>},relationships => #{},type => <<"symptom">>}],...}],...},...]},...},...}
2021-05-31 09:07:59.241 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-31 09:07:59.247 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-31 09:07:59.254 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-31 09:07:59.254 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-31 09:07:59.254 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-31 09:07:59.254 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-31 09:07:59.271 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-31 09:07:59.271 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-31 09:07:59.283 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-31 09:07:59.285 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-31 09:07:59.439 [warning] <0.391.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-31 09:07:59.522 [info] <0.44.0> Application api_test started on node nonode@nohost
2021-05-31 09:28:18.484 [info] <0.44.0> Application lager started on node nonode@nohost
2021-05-31 09:28:18.490 [info] <0.44.0> Application xmerl started on node nonode@nohost
2021-05-31 09:28:18.497 [info] <0.44.0> Application sasl started on node nonode@nohost
2021-05-31 09:28:18.497 [info] <0.44.0> Application tools started on node nonode@nohost
2021-05-31 09:28:18.497 [info] <0.44.0> Application jsx started on node nonode@nohost
2021-05-31 09:28:18.497 [info] <0.44.0> Application recon started on node nonode@nohost
2021-05-31 09:28:18.512 [info] <0.44.0> Application credentials_obfuscation started on node nonode@nohost
2021-05-31 09:28:18.512 [info] <0.44.0> Application rabbit_common started on node nonode@nohost
2021-05-31 09:28:18.524 [info] <0.44.0> Application amqp_client started on node nonode@nohost
2021-05-31 09:28:18.525 [info] <0.44.0> Application amqp started on node nonode@nohost
2021-05-31 09:28:18.671 [warning] <0.391.0> AMQP 0-9-1 client call timeout was 60000 ms, is updated to a safe effective value of 70000 ms
2021-05-31 09:28:18.749 [info] <0.44.0> Application api_test started on node nonode@nohost
